### ISSUE TITLE
Resume program

### ISSUE THREAD

**Issue by akataz04** [FlyingDiver/Indigo-Trane-Nexia#19]
Getting the error:

Trane Home Error                plugin does not define method actionResumeProgram

**Comment by FlyingDiver** [comment]
What are you doing when you get that error?

**Comment by FlyingDiver** [comment]
Oh, nevermind.  The "Resume Program" action isn't even supposed to be listed.    I'll remove it next update.

You need to use "Zone Return to Scheduled Operation".

**Comment by FlyingDiver** [comment]
Obsoleted by plugin rewrite.  Open new issue if this reoccurs with 2022.1.0 or later.
