### ISSUE TITLE
Write Thermostat Data to Log fails

### ISSUE THREAD

**Issue by stoney** [FlyingDiver/Indigo-Trane-Nexia#9]
I was trying to determine why I couldn't make a 2nd Zone device for my 2nd thermostat (the 1st one was fine), and Mr. Diver asked me to put the output of "Write Thermostat Data to Log" here. When I chose that command, I got an error (repeatable).

   Trane Nexia Debug               menuDumpThermostat
   Trane Nexia Error               Error in plugin execution MenuAction:

Traceback (most recent call last):
  File "plugin.py", line 438, in menuDumpThermostat
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Trane Nexia.indigoPlugin/Contents/Server Plugin/nexia_thermostat.py", line 302, in _get_thermostat_json
IndexError: More than one thermostat detected. You must provide a thermostat_id

**Comment by FlyingDiver** [comment]
Ok, obviously I never tried that command on an account with multiple thermostats.  As I said, I only have one (which has two zones).  I'll need to do some research on this.

**Comment by FlyingDiver** [comment]
Obsoleted by plugin rewrite. Open new issue if this reoccurs with 2022.1.0 or later.
